# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEvaluationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_value', models.CharField(max_length=50)),
                ('high_value', models.FloatField()),
                ('low_value', models.FloatField()),
                ('close_value', models.FloatField()),
                ('volume', models.FloatField()),
                ('adj_close', models.FloatField()),
            ],
        ),
    ]
