# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataplot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamEvaluationCriteria',
            new_name='ChartData',
        ),
    ]
