# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplot', '0004_auto_20170214_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
