# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplot', '0005_auto_20170328_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='date',
            field=models.FloatField(default=0.0),
        ),
    ]
